import numpy as np
import matplotlib.pyplot as plt
plt.figure(figsize=[10, 8])
Inicial=(431,275,301,156,202)
Primaria=(831,515,916,413,610)
Secundaria=(1022,445,856,412,514)
Especial=(93,217,141,51,35)
X = np.arange(len(Inicial))
plt.bar(X, Inicial, color = 'black',edgecolor='black',linewidth=2, width = 0.2)
plt.bar(X + 0.2, Primaria, color = 'g',edgecolor='black',linewidth=2, width = 0.2)
plt.bar(X + 0.4, Secundaria, color = 'b',edgecolor='black',linewidth=2, width = 0.2)
plt.bar(X + 0.6, Especial, color='r',edgecolor='black',linewidth=2, width=0.2)
plt.legend(['inicial', 'primaria', 'secundaria','Especial'])
plt.xticks([i + 0.2 for i in range(5)], ['Cajamarca', 'Callao', 'Cusco', 'Huancavelica', 'Huanuco'])
plt.title("Profesores por regiones")
plt.xlabel('Regiones')
plt.ylabel('Profesores')
plt.savefig('proyecto4.png')
plt.show()